baseURL = "http://stevenstetzler.com/recipes"
languageCode = "en-us"
title = "Recipes"

[params]

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
